name: GitHub Classroom Workflow

# the autograder action does not have access to environment variables
# the autograder action does not seem to use the maven cache

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Homework Repository
        uses: actions/checkout@v2

      - name: Setup Homework Test Environment
        uses: usf-cs212-fall2020/action-homework-setup@main

      - name: Setup Java JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Autograder
        uses: education/autograding@v1
